server:
  port: 8018

kafka:
  custom:
    config:
      bootstrap-server: localhost:9092
      schema-registry: http://localhost:8081
      zoo-keeper-server: localhost:2181
      security-protocol: PLAINTEXT

request:
  expiry:
    time: 20000

logging:
  level:
    com:
      tsb.onboarding: DEBUG
